// Code generated by interfacer; DO NOT EDIT

package busagent

import (
	"github.com/godbus/dbus/v5"
)

// BusAgent is an interface generated for "github.com/black-desk/busagent/internal/busagent.impl".
type BusAgent interface {
	PropGet(string, dbus.ObjectPath, string) error
}
